name: esc_pos_printer
description: The library allows to print receipts using an ESC/POS thermal WiFi printer.
version: 5.0.0
homepage: https://github.com/andrey-ushakov/esc_pos_printer

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  charset_converter: ^2.1.1
  flutter_esc_pos_utils: ^1.0.0
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
